import 'lexicon.dart';

/// German receipt vocabulary (DE, AT, CH). Umlauts are folded before matching,
/// so `rückgeld` is written `ruckgeld`.
const germanLexicon = Lexicon(
  languageCode: 'de',
  totalStrong: [
    'summe',
    'gesamt',
    'gesamtbetrag',
    'gesamtsumme',
    'endsumme',
    'endbetrag',
    'zu zahlen',
    'zahlbetrag',
    'rechnungsbetrag',
  ],
  totalWeak: ['betrag'],
  totalNegative: [
    'zwischensumme',
    'ruckgeld',
    'rueckgeld',
    'gegeben',
    'bar',
    'bargeld',
    'netto',
    'rabatt',
    'ersparnis',
    'gespart',
    'sie sparen',
    'pfand',
    'rundung',
  ],
  subtotal: ['zwischensumme', 'zw summe', 'zwsumme'],
  tax: ['mwst', 'ust', 'mehrwertsteuer', 'umsatzsteuer', 'steuer'],
  taxIncludedStatement: ['enthalten', 'enthaltene', 'enthalt', 'enthaltener'],
  taxIncludedTotal: ['inkl', 'inklusive'],
  tip: ['trinkgeld'],
  dateLabels: ['datum'],
  dateNoise: ['gultig', 'gultig bis', 'bis', 'mhd', 'haltbar', 'umtausch'],
  months: {
    'januar': 1,
    'janner': 1,
    'jan': 1,
    'februar': 2,
    'feb': 2,
    'marz': 3,
    'maerz': 3,
    'mrz': 3,
    'april': 4,
    'apr': 4,
    'mai': 5,
    'juni': 6,
    'jun': 6,
    'juli': 7,
    'jul': 7,
    'august': 8,
    'aug': 8,
    'september': 9,
    'sep': 9,
    'oktober': 10,
    'okt': 10,
    'november': 11,
    'nov': 11,
    'dezember': 12,
    'dez': 12,
  },
  merchantNoise: [
    'rechnung',
    'kassenbon',
    'kassenbeleg',
    'beleg',
    'bon',
    'quittung',
    'ust idnr',
    'ust id',
    'steuernummer',
    'steuer nr',
    'st nr',
    'filiale',
    'kasse',
    'vielen dank',
    'danke',
    'willkommen',
    'herzlich willkommen',
    'kundenbeleg',
    'handlerbeleg',
    'tel',
    'telefon',
    'offnungszeiten',
  ],
  streetSuffixes: ['strasse', 'str', 'weg', 'platz', 'allee', 'gasse', 'damm'],
  card: [
    'ec karte',
    'ec',
    'girocard',
    'kartenzahlung',
    'karte',
    'kreditkarte',
    'maestro',
    'vpay',
    'kontaktlos',
  ],
  cash: ['bar', 'bargeld', 'gegeben'],
  paymentNoise: ['payback', 'kundenkarte', 'punkte', 'bonus'],
  tableNet: ['netto', 'netto betrag'],
  tableGross: ['brutto', 'umsatz'],
);
