import 'lexicon.dart';

/// English receipt vocabulary (AU, US, UK, CA, NZ, IE, IN, …).
const englishLexicon = Lexicon(
  languageCode: 'en',
  totalStrong: [
    'total',
    'grand total',
    'total due',
    'amount due',
    'balance due',
    'total amount',
    'amount payable',
    'total payable',
    'to pay',
    'total to pay',
    'order total',
    'sale total',
  ],
  totalWeak: ['balance', 'amount', 'purchase', 'sale', 'due'],
  totalNegative: [
    'subtotal',
    'sub total',
    'change',
    'change due',
    'cash',
    'tendered',
    'rounding',
    'round',
    'savings',
    'saved',
    'you saved',
    'discount',
    'points',
    'items',
    'qty',
    'net',
    'cash out',
    'cashout',
    'surcharge',
    'deposit',
    'refund',
  ],
  subtotal: ['subtotal', 'sub total', 'sub ttl', 'subttl'],
  tax: [
    'gst',
    'vat',
    'tax',
    'sales tax',
    'hst',
    'pst',
    'qst',
    'tva',
    'iva',
    'btw',
  ],
  taxIncludedStatement: ['includes', 'included', 'include'],
  taxIncludedTotal: ['inc', 'incl', 'including', 'inclusive', 'inclusive of'],
  tip: ['tip', 'gratuity'],
  tipSuggestion: ['suggested', 'suggestion', 'guide', 'would be'],
  dateLabels: ['date', 'dated', 'date of sale', 'purchase date'],
  dateNoise: [
    'exp',
    'expiry',
    'expires',
    'valid',
    'until',
    'best before',
    'use by',
    'return',
    'returns',
    'refund',
    'member since',
    'birthday',
  ],
  months: {
    'january': 1,
    'jan': 1,
    'february': 2,
    'feb': 2,
    'march': 3,
    'mar': 3,
    'april': 4,
    'apr': 4,
    'may': 5,
    'june': 6,
    'jun': 6,
    'july': 7,
    'jul': 7,
    'august': 8,
    'aug': 8,
    'september': 9,
    'sept': 9,
    'sep': 9,
    'october': 10,
    'oct': 10,
    'november': 11,
    'nov': 11,
    'december': 12,
    'dec': 12,
  },
  merchantNoise: [
    'tax invoice',
    'invoice',
    'receipt',
    'sales receipt',
    'welcome',
    'welcome to',
    'thank you',
    'thanks',
    'customer copy',
    'merchant copy',
    'copy',
    'duplicate',
    'reprint',
    'order',
    'table',
    'server',
    'guest',
    'guests',
    'check',
    'cashier',
    'operator',
    'terminal',
    'abn',
    'acn',
    'vat no',
    'vat reg',
    'vat number',
    'vat registration',
    'tel',
    'phone',
    'ph',
    'fax',
    'www',
    'http',
    'https',
    'email',
    'open',
    'hours',
    'trans',
    'transaction',
    'date',
    'time',
    'reg',
    'store no',
    'store number',
  ],
  streetWords: [
    'street',
    'st',
    'road',
    'rd',
    'avenue',
    'ave',
    'av',
    'boulevard',
    'blvd',
    'lane',
    'ln',
    'drive',
    'dr',
    'highway',
    'hwy',
    'parade',
    'pde',
    'place',
    'pl',
    'court',
    'ct',
    'terrace',
    'tce',
    'way',
    'square',
    'sq',
    'crescent',
    'cres',
    'close',
    'shop',
    'unit',
    'suite',
    'ste',
    'level',
    'centre',
    'center',
    'plaza',
    'mall',
    'po box',
  ],
  card: [
    'visa',
    'mastercard',
    'master card',
    'mc',
    'amex',
    'american express',
    'discover',
    'maestro',
    'eftpos',
    'debit',
    'credit',
    'card',
    'contactless',
    'paypass',
    'paywave',
    'apple pay',
    'google pay',
    'chip',
  ],
  cash: ['cash', 'tendered', 'cash tendered'],
  paymentNoise: [
    'cash out',
    'cashout',
    'rewards',
    'reward',
    'loyalty',
    'points',
    'member',
    'membership',
    'club',
    'clubcard',
    'nectar',
    'flybuys',
    'gift card',
    'we accept',
  ],
  tableNet: ['net', 'nett', 'excl', 'ex'],
  tableGross: ['gross', 'total', 'incl', 'inc', 'amount'],
);
